CREATE TABLE SINHVIEN
(
    MSSV    CHAR(6)          NOT NULL,
    TENSV   NVARCHAR2(40)    NOT NULL,
    SODT    CHAR(10)         NULL,
    LOP     NVARCHAR2(40)    NOT NULL,
    DIACHI  NVARCHAR2(100)   NOT NULL,
    CONSTRAINT PK_SINHVIEN PRIMARY KEY(MSSV)
);

CREATE TABLE DETAI
(
    MSDT    CHAR(6)         NOT NULL,
    TENDT   NVARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_DETAI PRIMARY KEY(MSDT)
);

CREATE TABLE SV_DETAI
(
    MSSV    CHAR(6)         NOT NULL,
    MSDT    CHAR(6)         NOT NULL,
    CONSTRAINT PK_SV_DETAI PRIMARY KEY(MSSV,MSDT)
);

CREATE TABLE GIAOVIEN
(
    MSGV    INT                 NOT NULL,
    TENGV   NVARCHAR2(40)       NOT NULL,
    DIACHI  NVARCHAR2(100)      NOT NULL,
    SODT    CHAR(10)            NULL,
    MSHHAM  INT                 NOT NULL,
    NAMHH   INT                 NULL,
    CONSTRAINT PK_GIAOVIEN PRIMARY KEY(MSGV)
);

CREATE TABLE HOCVI
(
    MSHV    INT             NOT NULL,
    TENHV   NVARCHAR2(20)   NOT NULL,
    CONSTRAINT PK_HOCVI PRIMARY KEY(MSHV)
);

CREATE TABLE CHUYENNGANH
(
    MSCN    INT             NOT NULL,
    TENCN   NVARCHAR2(30)   NOT NULL,
    CONSTRAINT PK_CHUYENNGANH PRIMARY KEY(MSCN)
);

CREATE TABLE GV_HV_CN
(
    MSGV    INT    NOT NULL,
    MSHV    INT    NOT NULL,
    MSCN    INT    NOT NULL,
    CONSTRAINT PK_GV_HV_CN PRIMARY KEY(MSGV,MSHV,MSCN)
);

CREATE TABLE HOCHAM
(
    MSHH    INT             NOT NULL,
    TENHH   NVARCHAR2(30)   NOT NULL,
    CONSTRAINT PK_HOCHAM PRIMARY KEY(MSHH)
);

CREATE TABLE GV_HDDT
(
    MSGV    INT     NOT NULL,
    MSDT    CHAR(6) NOT NULL,
    DIEM    FLOAT   NULL,
    CONSTRAINT PK_GV_HDDT PRIMARY KEY(MSGV,MSDT)
);

CREATE TABLE GV_PBDT
(
    MSGV    INT     NOT NULL,
    MSDT    CHAR(6) NOT NULL,
    DIEM    FLOAT   NULL,
    CONSTRAINT PK_GV_PBDT PRIMARY KEY(MSGV,MSDT)
);

CREATE TABLE GV_UVDT
(
    MSGV    INT     NOT NULL,
    MSDT    CHAR(6) NOT NULL,
    DIEM    FLOAT   NULL,
    CONSTRAINT PK_GV_UVDT PRIMARY KEY(MSGV,MSDT)
);

CREATE TABLE HOIDONG
(
    MSHD        INT          NOT NULL,
    PHONG       CHAR(10)     NULL,
    TGBD        CHAR(10)     NULL,
    NGAYHD      DATE         NULL,
    TINHTRANG   NVARCHAR2(30)NULL,
    MSGVCTHD    INT          NOT NULL,
    CONSTRAINT PK_HOIDONG PRIMARY KEY(MSHD)
);

CREATE TABLE HOIDONG_GV
(
    MSHD    INT     NOT NULL,
    MSGV    INT     NOT NULL,
    CONSTRAINT PK_HOIDONG_GV PRIMARY KEY(MSHD,MSGV)
);

CREATE TABLE HOIDONG_DT
(
    MSHD      INT           NOT NULL,
    MSDT      CHAR(6)       NOT NULL,
    QUYETDINH NVARCHAR2(30) NULL,
    CONSTRAINT PK_HOIDONG_DT PRIMARY KEY(MSHD,MSDT)
);

ALTER TABLE SV_DETAI
    ADD
        (
            CONSTRAINT FK_SV_DETAI_SINHVIEN 
            FOREIGN KEY(MSSV) REFERENCES SINHVIEN(MSSV),
            
            CONSTRAINT FK_SV_DETAI_DETAI
            FOREIGN KEY(MSDT) REFERENCES SINHVIEN(MSDT)
        );
        
ALTER TABLE GIAOVIEN
    ADD
        (
CONSTRAINT FK_GIAOVIEN_HOCHAM 
            FOREIGN KEY (MSHH) REFERENCES HOCHAM(MSHH)
        );
        
ALTER TABLE GV_HV_CN
    ADD
        (
            CONSTRAINT FK_GV_HV_CN_GIAOVIEN
            FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
            
            CONSTRAINT FK_GV_HV_CN_HOCVI
            FOREIGN KEY (MSHV) REFERENCES HOCVI(MSHV),
            
            CONSTRAINT FK_GV_HV_CN_CHUYENNGANH
            FOREIGN KEY (MSCN) REFERENCES CHUYENNGANH(MSCN)
        );
        
ALTER TABLE GV_HDDT
    ADD
        (
            CONSTRAINT FK_GV_HDDT_GIAOVIEN
            FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
            
            CONSTRAINT FK_GV_HDDT_DETAI
            FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
        );
        
ALTER TABLE GV_PBDT
    ADD
        (
            CONSTRAINT FK_GV_PBDT_GIAOVIEN
            FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
            
            CONSTRAINT FK_GV_PBDT_DETAI
            FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
        );
        
ALTER TABLE GV_UVDT
    ADD
        (
            CONSTRAINT FK_GV_UVDT_GIAOVIEN
            FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV),
            
            CONSTRAINT FK_GV_UVDT_DETAI
            FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
        );
        
ALTER TABLE HOIDONG_GV
    ADD
        (
            CONSTRAINT FK_HOIDONG_GV_HOIDONG
            FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
            
            CONSTRAINT FK_HOIDONG_GV_GIAOVIEN
            FOREIGN KEY (MSGV) REFERENCES GIAOVIEN(MSGV)
        );
        
ALTER TABLE HOIDONG_DT
    ADD
        (
            CONSTRAINT FK_HOIDONG_DT_HOIDONG
            FOREIGN KEY (MSHD) REFERENCES HOIDONG(MSHD),
            
            CONSTRAINT FK_HOIDONG_DT_DETAI
            FOREIGN KEY (MSDT) REFERENCES DETAI(MSDT)
        );

    
